/**
 * Common countries list for shipping address forms
 * Ghana is listed first as it's the primary market
 */
export const COUNTRIES = [
  "Ghana",
  "Nigeria",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "South Africa",
  "Kenya",
  "Tanzania",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Mozambique",
  "Malawi",
  "Rwanda",
  "Ethiopia",
  "Egypt",
  "Morocco",
  "Tunisia",
  "Algeria",
  "Senegal",
  "Ivory Coast",
  "Cameroon",
  "Gabon",
  "Congo",
  "Angola",
  "Mauritius",
  "Seychelles",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Philippines",
  "Indonesia",
  "Vietnam",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Lebanon",
  "Jordan",
  "Israel",
  "Turkey",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ecuador",
  "Panama",
  "Costa Rica",
  "Jamaica",
  "Trinidad and Tobago",
  "Barbados",
  "New Zealand",
  "Other",
].sort((a, b) => {
  // Keep Ghana first, then sort the rest alphabetically
  if (a === "Ghana") return -1;
  if (b === "Ghana") return 1;
  return a.localeCompare(b);
});
